site_name: MR24HPB1
site_description: Library for interacting with the MR24HPB1 sensor.
site_author: Teagan Glenn

repo_url: https://github.com/constructorfleet/MR24HPB1
edit_uri: https://github.com/constructorfleet/MR24HPB1/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
